outputs:
  - name: "parts_all"        
  - name: "parts_basic"
    keys: 
      - "short_code"
      - "name"
      - "classification"
      - "type"
      - "size"
      - "color"
      - "description_main"
      - "description_extra"
      - "manufacturer"
      - "part_number"
  - name: "bolt_helper"
    keys:
      - short_code
      - name
      - type
      - description_main
      - description_only_numbers
      - part_number_distributor_orbital_fasteners
      - webpage_distributor_orbital_fasteners
      - part_number_manufacturer_metalmate
      - webpage_manufacturer_metalmate 
      - price_current
      - price_1
      - name_manufacturer_metalmate
      - project_bolt_tray_capacity_oobb_6_width_2_5_length_18_mm_depth
      - project_bolt_tray_capacity_oobb_6_width_2_5_length_18_mm_depth_weight
      - project_bolt_tray_capacity_oobb_4_width_2_5_length_18_mm_depth
      - project_bolt_tray_capacity_oobb_4_width_2_5_length_18_mm_depth_weight
      - project_bolt_tray_capacity_oobb_2_5_width_2_length_18_mm_depth
      - project_bolt_tray_capacity_oobb_2_5_width_2_length_18_mm_depth_weight      
      - weight_10
      - weight





    